steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/code-analyze', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/code-analyze']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'code-analyze', '--image', 'gcr.io/$PROJECT_ID/code-analyze', '--region', 'us-central1','--allow-unauthenticated', '--platform', 'managed', '--memory', '2Gi', '--max-instances', '5', '--update-env-vars', 'PROJECT_ID=$PROJECT_ID']
images:
- gcr.io/$PROJECT_ID/code-analyze