steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prompt-guard-api-gpu', '.']
    id: BuildDockerImage

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prompt-guard-api-gpu']
    id: PushDockerImage

  # Step 3: Deploy to Google Cloud Run with Hugging Face token from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy prompt-guard-api-gpu \
          --image gcr.io/$PROJECT_ID/prompt-guard-api-gpu \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --cpu=4 \
          --memory=16Gi \
          --no-cpu-throttling \
          --max-instances=1 \
          --gpu=1 \
          --gpu-type=nvidia-l4 \
          --set-env-vars=HUGGING_FACE_HUB_TOKEN=$$HUGGING_FACE_HUB_TOKEN \
          --labels=service=prompt-guard
    secretEnv: ['HUGGING_FACE_HUB_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/234439745674/secrets/HUGGING_FACE_HUB_TOKEN/versions/1
      env: 'HUGGING_FACE_HUB_TOKEN'

images:
  - 'gcr.io/$PROJECT_ID/prompt-guard-api-gpu'

timeout: '1200s'
