steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prompt-guard-api-cpu', '.']
    id: BuildDockerImage

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prompt-guard-api-cpu']
    id: PushDockerImage

  # Step 3: Deploy to Google Cloud Run with Hugging Face token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'prompt-guard-api-cpu'  # Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/prompt-guard-api-cpu'
      - '--region'
      - 'us-central1'  # You can change the region as needed
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu=1'
      - '--memory=2Gi'
      - '--set-env-vars=HUGGING_FACE_HUB_TOKEN=$$HUGGING_FACE_HUB_TOKEN'
      - '--labels=service=prompt-guard'
    secretEnv: ['HUGGING_FACE_HUB_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/234439745674/secrets/HUGGING_FACE_HUB_TOKEN/versions/1
      env: 'HUGGING_FACE_HUB_TOKEN'

images:
  - 'gcr.io/$PROJECT_ID/prompt-guard-api-cpu'

timeout: '1200s'  # 20 minutes timeout for build and deployment
